### PR TITLE
Remove recursion in BlasMatMulVecAdd `materialize!`

### PR DESCRIPTION
**Pull request by jishnub**
This helps with TTFX
On master
```julia
julia> B = BandedMatrix(0=>ones(1000));

julia> v = ones(size(B,1));

julia> @time @eval B' * v;
  1.284047 seconds (4.66 M allocations: 537.080 MiB, 7.13% gc time, 99.22% compilation time)
```
This PR
```julia
julia> @time @eval B' * v;
  0.321558 seconds (784.08 k allocations: 52.189 MiB, 3.48% gc time, 96.75% compilation time)
```

### CODE REVIEW

**Comment by dlfivefifty** [comment]
It looks like there is code repeated (and actually was already repeated) between `_banded_muladd!` and `materialize!(::MulAdd{BandedRows,…})` here:

https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/blob/8e262c77da628758243a5cfe308d11444c6b8ad9/src/generic/matmul.jl#L71

Perhaps we can combine these two into a single function `_banded_rows_muladd!`?

**Comment by jishnub** [comment]
Test failure on nightly is due to https://github.com/JuliaLang/julia/issues/48427, and is likely to be fixed soon

**Comment by jishnub** [comment]
Gentle bump, I think this should be good to go. Test failure on nightly is unrelated

**Comment by jishnub** [comment]
The issue on nightly is resolved now, and it would be good to move this forward

**Pull request merged**
